# healthcheck-alerts.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: healthcheck-app-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: healthcheck-app.rules
      rules:
        - alert: PodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total{namespace="default"}[15m]) > 3
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} is crash-looping"
            description: "Pod {{ $labels.pod }} has restarted more than 3 times in the last 15 minutes."