# values.yaml
grafana:
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi

prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
    retention: 6h

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m

# Disable components we don't need for a single-node learning cluster
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
