grafana:
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
  service:
    type: NodePort
    nodePort: 30310

prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
    retention: 6h
  service:
    type: NodePort
    nodePort: 30320

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
  service:
    type: NodePort
    nodePort: 30330

# Disable components we don't need for a single-node learning cluster
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
