- name: Deploy new image via SSM
  env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          ECR_REPOSITORY: healthcheck-app
          IMAGE_TAG: ${{ github.sha }}
          INSTANCE_ID: i-0e5efb81d299c9944
 run: |
    aws ssm send-command \
     --instance-ids $INSTANCE_ID \
     --document-name "AWS-RunShellScript" \
     --parameters "commands=[\"export KUBECONFIG=/home/ec2-user/.kube/config && kubectl set image deployment/healthcheck-app healthcheck-app=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -n default\"]" \
  --region eu-west-1